### ISSUE TITLE
Lots of sessions don't have any real information, is confusing

### ISSUE THREAD

**Issue by autonome** [mdn/viewsourceconf#131]
A lot of the schedule looks barren and incomplete.

If a session is a discussion, we should make that clear by prefixing with "Discussion: ", and the workshops we should prefix with "Workshop: ".

We should add who is leading the sessions/workshops and add actual descriptions about what it will consist of.

Dominique Hazael-Massieux's session doesn't have any info, just "webVR".

Both of the PWA sessions are described as discussions, not hacking, so maybe we should change the titles.

It's also not clear that there are multiple runs of the same sessions/discussions. Looks like Stephanie might've made that better in her pull request though.

**Comment by hoosteeno** [comment]
Thanks for the issue -- keep 'em coming!

We're publishing the content we have just as soon as we have it. Every talk will have a picture next to it and a summary. But rounding those up can take days or weeks. Instead of waiting to have everything, we're publishing what we have when we have it. Hopefully the disclaimer at the top excuses the gaps somewhat.

Here's what @stephaniehobson's PR does:

https://github.com/mdn/viewsourceconf/pull/129#issuecomment-236700862

We'll keep adding content. We'll definitely r? and merge good PRs, if you see something you want to contribute!

**Comment by hoosteeno** [comment]
We just launched a minor refactor of schedule data and updated the UI to make it less confusing. Also a lot more content landed. We've tried to work around the fact that we have imperfect information about some sessions. Let us know how it's working for you.

**Comment by autonome** [comment]
Bazillion times better, thanks!
